assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE02SHSP-SP001-01-DOSTAJ000
stream:
  method: telemetered
  name: dosta_abcdjm_cspp_instrument
workflow_config:
  schedule: 0 0 * * *
